apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-social
spec:
  selector:
    matchLabels:
      app: developer-social
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: developer-social
    spec:
      containers:
        - name: developer-social
          image: steven8519/developer-social
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: devhub
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: developer-social
  ports:
    - name: http
      port: 8001
  type: ClusterIP
