apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    appdb: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: mongodb
  template:
    metadata:
      labels:
        appdb: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.6
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    appdb: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: developers
  labels:
    app: developers
    service: developers
spec:
  ports:
    - port: 8001
      name: http
  selector:
    app: developers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developers-hub
  labels:
    account: developers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developers-v1
  labels:
    app: developers
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developers
      version: v1
  template:
    metadata:
      labels:
        app: developers
        version: v1
    spec:
      serviceAccountName: developers-hub
      containers:
        - name: developers
          image: steven8519/developer-social
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
