apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-social
spec:
  selector:
    matchLabels:
      app: developer-social
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: developer-social
    spec:
      containers:
        - name: devhub
          image: steven8519/developer-social
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: developer-social
  labels:
    app: developer-social
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: developer-social
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    appdb: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: mongodb
  template:
    metadata:
      labels:
        appdb: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.6
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    appdb: mongodb
