apiVersion: v1
kind: Service
metadata:
  name: dev-service
  labels:
    app: dev-service
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: dev-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-service
        version: v1
    spec:
      containers:
        - name: devhub-app
          image: steven8519/developer-social
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    appdb: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: mongodb
  template:
    metadata:
      labels:
        appdb: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.6
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    appdb: mongodb
