apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-social
spec:
  selector:
    matchLabels:
      app: developer-social
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: developer-social
    spec:
      containers:
        - name: position-tracker
          image: steven8519/developer-social
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: developers-devhub-social
spec:
  selector:
    app: developer-social
  ports:
    - name: http
      port: 8001
  type: ClusterIP
