apiVersion: v1
kind: Service
metadata:
  name: dev-social
  labels:
    app: dev-social
spec:
  ports:
    - name: http
      port: 8001
  selector:
    app: dev-social
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-social
spec:
  selector:
    matchLabels:
      app: dev-social
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: dev-social
    spec:
      containers:
        - name: dev-social
          image: steven8519/developer-social
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8001
            livenessProbe:
              httpGet:
                path: /
                port: 8001
              initialDelaySeconds: 5
              periodSeconds: 5
