spring:
  profiles:
    active: test
server:
  port:
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  profiles: prod
  data:
    mongodb:
      host: mongodb
      port: 27017
server:
  port: 8001
